// Generated by https://quicktype.io

export interface ObjectProduct {
  id:           number;
  date_create:  null;
  random:       number;
  random_float: number;
  bool:         boolean;
  regex:        string;
  enun:         string;
  elt:          string;
  age:          number;
}
